# Generated by Django 2.2 on 2022-09-15 19:07

from django.db import migrations


def fill_db(apps, schema_editor):
    author = apps.get_model('advertisements_app', 'Author')
    author.objects.all().delete()
    for i in range(1, 10):
        author.objects.create(name='автор ' + str(i), phone='8-800-300-10-0' + str(i), email='mail{}@mail.ru'.format(i))

    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    advertisement_category = apps.get_model('advertisements_app', 'AdvertisementCategory')
    advertisement_category.objects.all().delete()
    advertisement_category.objects.create(name='Авто')
    advertisement_category.objects.create(name='Недвижимость')
    advertisement_category.objects.create(name='Работа')

    advertisement = apps.get_model('advertisements_app', 'Advertisement')
    advertisement.objects.all().delete()

    for i in range(1, 3):
        advertisement.objects.create(title='заголовок ' + str(i),
                                     price=10,
                                     description=('Описание ' + str(i))*10,
                                     category=advertisement_category.objects.get(name='Работа'),
                                     author=author.objects.get(name='автор ' + str(i)))

    for i in range(3, 5):
        advertisement.objects.create(title='заголовок ' + str(i),
                                     price=10,
                                     description=('Описание ' + str(i))*10,
                                     category=advertisement_category.objects.get(name='Недвижимость'),
                                     author=author.objects.get(name='автор ' + str(i)))

    for i in range(5, 10):
        advertisement.objects.create(title='заголовок ' + str(i),
                                     price=10,
                                     description=('Описание ' + str(i))*10,
                                     category=advertisement_category.objects.get(name='Авто'),
                                     author=author.objects.get(name='автор ' + str(i)))


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0005_auto_20220915_1603'),
    ]

    operations = [migrations.RunPython(fill_db)]
