# Generated by Django 4.1.2 on 2022-11-10 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('balance', models.FloatField(verbose_name='Баланс')),
                ('status', models.CharField(choices=[('З', 'Золото'), ('C', 'Серебро'), ('Б', 'Бронза')], max_length=1000, verbose_name='Статус')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='storage_products', to='marketplace_cite.product', verbose_name='Товар')),
                ('shop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='storage_shops', to='marketplace_cite.shop', verbose_name='Магазин')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='marketplace_cite.product', verbose_name='Товар')),
                ('shop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shops', to='marketplace_cite.shop', verbose_name='Магазин')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_profiles', to='marketplace_cite.userprofile', verbose_name='Профиль пользователя')),
            ],
        ),
    ]
