# Generated by Django 4.1.3 on 2022-11-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_cite', '0003_alter_product_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AddField(
            model_name='basket',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
