# Generated by Django 4.1.3 on 2022-11-13 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_cite', '0004_alter_basket_options_basket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users_bascket', to='marketplace_cite.userprofile', verbose_name='Пользователь'),
        ),
    ]
