# Generated by Django 4.1.3 on 2022-11-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_cite', '0006_alter_basket_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='BasketItem',
        ),
    ]
