# Generated by Django 4.1.3 on 2022-11-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_cite', '0007_rename_basket_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
