# Generated by Django 2.2 on 2022-10-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('record', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_image', to='files_test.Record', verbose_name='Запись')),
            ],
        ),
    ]
