# Generated by Django 2.2 on 2022-10-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_test', '0002_recordfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfiles',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='files/'),
        ),
    ]
