# Generated by Django 2.2 on 2022-10-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_test', '0003_auto_20221012_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='title',
        ),
        migrations.AlterField(
            model_name='recordfiles',
            name='record',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='files_test.Record', verbose_name='Запись'),
        ),
    ]
