# Generated by Django 2.2 on 2022-10-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_test', '0004_auto_20221012_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='record',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
