# Generated by Django 2.2 on 2022-10-13 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_test', '0006_auto_20221013_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
    ]
