# Generated by Django 2.2 on 2022-10-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_shops_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('shop', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_shop', to='shop.Shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
