# Generated by Django 2.2 on 2022-10-22 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_add_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата покупки'),
        ),
    ]
