# Generated by Django 2.2 on 2022-10-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_one', models.CharField(max_length=100, verbose_name='field one')),
                ('field_two', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='field two')),
            ],
            options={
                'verbose_name': 'test model',
                'verbose_name_plural': 'test model',
            },
        ),
    ]
