# Generated by Django 2.2 on 2022-09-22 10:49

from django.db import migrations
from random import randint


def fill_db(apps, schema_editor):
    news = apps.get_model('app_news', 'News')
    news.objects.all().delete()
    for i in range(1, 20):
        news.objects.create(title='Новость {}'.format(i),
                            description=('Описание {} '.format(i))*30,
                            is_active=True)

    comments = apps.get_model('app_news', 'Comment')
    comments.objects.all().delete()

    users = apps.get_model('app_news', 'User')
    users.objects.all().delete()
    for i in range(1, 5):
        users.objects.create(user_name='Пользователь {}'.format(i))

    for i in range(1, 20):
        for j in range(1, randint(2, 10)):
            user_name = 'Пользователь {}'.format(randint(1, 4))
            comments.objects.create(user=users.objects.get(user_name=user_name),
                                    description='Комментарий {}'.format(j),
                                    news=news.objects.get(title='Новость {}'.format(i)))


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_auto_20220924_2126'),
    ]

    operations = [migrations.RunPython(fill_db)]
