# Generated by Django 2.2 on 2022-09-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_auto_20220924_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('p', 'published'), ('d', 'deleted')], default='p', max_length=1),
        ),
    ]
