# Generated by Django 2.2 on 2022-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('p', 'опубликовано'), ('d', 'удалено администратором')], default='p', max_length=1),
        ),
    ]
