# Generated by Django 2.2 on 2022-09-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0008_auto_20220924_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('p', 'опубликовано'), ('d', 'удалено администратором')], default='p', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'активна'), (False, 'неактивнам')], default=True, verbose_name='Активна'),
        ),
    ]
