# Generated by Django 2.2 on 2022-09-28 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_news', '0010_auto_20220927_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, verbose_name='Телефон')),
                ('town', models.CharField(max_length=100, verbose_name='Город')),
                ('news_cnt', models.IntegerField(default=0, verbose_name='Количество новостей')),
                ('verification', models.BooleanField(choices=[(True, 'да'), (False, 'нет')], default=False, verbose_name='Верифицирован')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='app_news.UserProfile', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
