# Generated by Django 2.2 on 2022-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_auto_20220928_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=None, max_length=10, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='town',
            field=models.CharField(default=None, max_length=100, verbose_name='Город'),
        ),
    ]
