# Generated by Django 2.2 on 2022-09-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0015_auto_20220929_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_moderator',
            field=models.BooleanField(choices=[(True, 'да'), (False, 'нет')], default=False, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='moderator_request',
            field=models.BooleanField(choices=[(True, 'да'), (False, 'нет')], default=False, verbose_name='Запрос на модерацию'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_request',
            field=models.BooleanField(choices=[(True, 'да'), (False, 'нет')], default=False, verbose_name='Запрос на верификацию'),
        ),
    ]
