# Generated by Django 2.2 on 2022-09-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0016_auto_20220930_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='moderator_request',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verification',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_request',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_request',
            field=models.BooleanField(choices=[(0, 'Нет'), (1, 'Запрос верификации'), (2, 'Стать модератором')], default=0, verbose_name='Запрос'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_state',
            field=models.BooleanField(choices=[(0, 'Обычный пользователь'), (1, 'Верифицированный пользователь'), (2, 'Модератор пользователь')], default=0, verbose_name='Статус'),
        ),
    ]
