# Generated by Django 2.2 on 2022-10-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0019_auto_20220930_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('usualuser', 'обычный пользователь'), ('verificateduser', 'верифицированный пользователь'), ('moderator', 'модератор'))},
        ),
    ]
