# Generated by Django 2.2 on 2022-09-22 10:49

from django.db import migrations
from random import randint
from django.contrib.auth.hashers import make_password


def fill_db(apps, schema_editor):

    comments = apps.get_model('app_news', 'Comment')
    comments.objects.all().delete()

    users = apps.get_model('auth', 'User')
    users_profiles = apps.get_model('app_news', 'UserProfile')
    for i in range(1, 10):

        if i >= 2 and i <= 5: # пользователи с запросом верификации
            users.objects.create(username='User_{}'.format(i), password=make_password('User_{}'.format(i)))
            user = users.objects.get(username='User_{}'.format(i))
            users_profiles.objects.create(user=user, phone=str(i)*10, town='Город {}'.format(i), user_request=1)
        elif i == 6 or i == 7: # верифицированные пользователи
            users.objects.create(username='User_{}'.format(i), password=make_password('User_{}'.format(i)))
            user = users.objects.get(username='User_{}'.format(i))
            users_profiles.objects.create(user=user, phone=str(i) * 10, town='Город {}'.format(i), user_state=1)
        elif i == 8: # модератор
            users.objects.create(username='User_{}'.format(i), password=make_password('User_{}'.format(i)))
            user = users.objects.get(username='User_{}'.format(i))
            users_profiles.objects.create(user=user, phone=str(i) * 10, town='Город {}'.format(i), user_state=2)
        else: # обычный пользователь
            users.objects.create(username='User_{}'.format(i), password=make_password('User_{}'.format(i)))
            user = users.objects.get(username='User_{}'.format(i))
            users_profiles.objects.create(user=user, phone=str(i) * 10, town='Город {}'.format(i))

    news = apps.get_model('app_news', 'News')
    news.objects.all().delete()
    for i in range(1, 20):
        user_name = 'User_{}'.format(randint(6, 7))
        ch = randint(1, 2)
        if ch == 1:
            news.objects.create(user=users.objects.get(username=user_name),
                                title='Новость {}'.format(i),
                                description=('Описание {} '.format(i))*30,
                                is_active=True)
        else:
            news.objects.create(user=users.objects.get(username=user_name),
                                title='Новость {}'.format(i),
                                description=('Описание {} '.format(i)) * 30,
                                is_active=False)

    for i in range(1, 20):
        for j in range(1, randint(2, 10)):
            user_name = 'User_{}'.format(randint(1, 9))
            comments.objects.create(user=users.objects.get(username=user_name),
                                    description='Комментарий {}'.format(j),
                                    news=news.objects.get(title='Новость {}'.format(i)))

    for i in range(1, 10):
        user = users.objects.get(username='User_{}'.format(i))
        profile = users_profiles.objects.get(user=user)
        profile.news_cnt = news.objects.filter(user=user).count()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0025_news_user'),
    ]

    operations = [migrations.RunPython(fill_db)]
