# Generated by Django 2.2 on 2022-10-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0025_news_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.CharField(default='', max_length=10, verbose_name='Тег'),
        ),
    ]
