# Generated by Django 4.1.2 on 2022-11-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ManyToManyField(to='library_api.author')),
                ('book', models.ManyToManyField(to='library_api.book')),
            ],
            options={
                'verbose_name': 'Авторское право',
                'verbose_name_plural': 'Авторские права',
            },
        ),
    ]
