# Generated by Django 4.1.2 on 2022-11-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0003_authorrules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorrules',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authorrules',
            name='book',
        ),
        migrations.AddField(
            model_name='authorrules',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='library_api.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='authorrules',
            name='book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='library_api.book', verbose_name='Книга'),
        ),
    ]
