# Generated by Django 4.1.2 on 2022-11-03 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0004_remove_authorrules_author_remove_authorrules_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='library_api.author', verbose_name='Автор'),
        ),
        migrations.DeleteModel(
            name='AuthorRules',
        ),
    ]
